### ISSUE TITLE
Test & Document Quark Server with SQLite 

### ISSUE THREAD

**Issue by vrajat** [qubole/quark#68]
Tests with SQLite. Need to make sure that it works with H2 on file and data is available between restarts. Also a doc is required on how to set it up.

**Comment by adeshr** [comment]
Migration fails with SQLite as SQLite doesn't support `ALTER TABLE` command for `ADD FOREIGN KEY`/`DROP COLUMN`. Also different syntax for SQLite as compared to H2/SQL will force to have a completely different set of migration for SQLite. Maintaining two sets of migration is error-prone, hence SQLite will not be supported for Quark.

**Comment by vrajat** [comment]
Since Quark works with H2. Lets close this issue.
