### ISSUE TITLE
Accessing quark through sqlline

### ISSUE THREAD

**Issue by anupamaggarwal** [qubole/quark#96]
Hi,  I am trying to start sqlline as per documentation in the source code, using the following connection string:-
!connect jdbc:quark:model.json com.qubole.quark.jdbc.QuarkDriver

However I get an error saying no driver to handle jdbc:quark:model.json

Is the documentation updated? I downloaded the relevant quark jdbc and sqlline (and jline) jars from maven. I am running this locally and the model.json is in the same folder as the jars

Can you please help

Thanks

**Comment by vrajat** [comment]
Hi @anupamaggarwal this project is not maintained anymore. We've moved these features into Qubole's distribution of Hive, Presto and Spark.

Is there a particular reason why you are experimenting with Quark ? Maybe I can help out with that.

**Comment by anupamaggarwal** [comment]
Thanks Rajat, appreciate the response. 

I am hoping to build something very similar to Quark (inspired largely by your presentation on quark -Hadoop summit) , with the objective of query federation across multiple database backends (hive,presto,mysql, Teradata) and possibly cloud (big-query,redshift etc).I plan to leverage the materialized view, query rewriting features of calcite to enable this and also cater to query execution lifecycle management. End goal is an arbitration layer for queries (some sort of Cost based optimizer) which can re-route amongst multiple possible rewrites (on multiple backends) for the same query.

  Was just trying to setup quark locally to experiment and ran into some issues.  I am probably a bit further away from my understanding (of both calcite and quark) to be asking specific questions but my very high level approach is to use current calcite codebase and merge some of the code in quark-catalog and quark-optimizer to implement this idea...would this be the right approach

Would love to learn from your experience, is this something which is feasible at scale?  (Any other generic pointers /codebases which could help out would be greatly appreciated too)

Thanks so much :)

-Anupam

**Comment by vrajat** [comment]
I suggest you start with prestodb. It has a much richer set of connectors already available and some intelligence to push down logic into the federated databases. 
Once you have that working, build in materialized views in Presto. One problem is that Presto CBO is still maturing. You could plugin the calcite/quark optimizer just for MV functionality.

**Comment by anupamaggarwal** [comment]
thanks for the suggestion Rajat, will checkout presto. I should have clarified, I was hoping to do the execution in the DB engine itself (for example if some columns  corresponding to a table are in mysql rerouting queries referencing those columns to mysql through MV rewrite instead of hive).  Maybe it makes more sense to do the execution in presto (depending on how much it's able to push down).

**Comment by vrajat** [comment]
You can still do that in Presto with a similar amount of work as Quark. The nice part is that you have a working version right from the start with very little push down of logic to Presto. Over a period of time, you can incrementally push down more execution through the connectors. The chances of success is much higher this way.

**Comment by anupamaggarwal** [comment]
Thanks Rajat for your suggestions, much appreciated!  will experiment with Presto.

**Comment by vrajat** [comment]
Great! I am closing this issue.
